// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
)

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $1 WHERE id = $2
`

type UpdateOrderStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}
