// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (user_id, name, size, content_type, storage_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, size, content_type, storage_key, created_at
`

type CreateFileParams struct {
	UserID      uuid.UUID
	Name        string
	Size        int64
	ContentType string
	StorageKey  string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.UserID,
		arg.Name,
		arg.Size,
		arg.ContentType,
		arg.StorageKey,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = $1 AND user_id = $2
`

type DeleteFileParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteFile, arg.ID, arg.UserID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, name, size, content_type, storage_key, created_at
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listFilesByUser = `-- name: ListFilesByUser :many
SELECT id, user_id, name, size, content_type, storage_key, created_at
FROM files
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFilesByUser(ctx context.Context, userID uuid.UUID) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Size,
			&i.ContentType,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
