// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	KeyHash   string
	Name      string
	CreatedAt time.Time
}

type File struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Size        int64
	ContentType string
	StorageKey  string
	CreatedAt   time.Time
}

type Share struct {
	ID             uuid.UUID
	FileID         uuid.UUID
	UserID         uuid.UUID
	Token          string
	RecipientEmail string
	ExpiresAt      sql.NullTime
	CreatedAt      time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
