// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shares.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (file_id, user_id, token, recipient_email, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, file_id, user_id, token, recipient_email, expires_at, created_at
`

type CreateShareParams struct {
	FileID         uuid.UUID
	UserID         uuid.UUID
	Token          string
	RecipientEmail string
	ExpiresAt      sql.NullTime
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, createShare,
		arg.FileID,
		arg.UserID,
		arg.Token,
		arg.RecipientEmail,
		arg.ExpiresAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.Token,
		&i.RecipientEmail,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShareByToken = `-- name: GetShareByToken :one
SELECT s.id, s.file_id, s.user_id, s.token, s.recipient_email, s.expires_at, s.created_at,
       f.name AS file_name, f.size AS file_size, f.content_type AS file_content_type, f.storage_key AS file_storage_key
FROM shares s
JOIN files f ON f.id = s.file_id
WHERE s.token = $1
`

type GetShareByTokenRow struct {
	ID              uuid.UUID
	FileID          uuid.UUID
	UserID          uuid.UUID
	Token           string
	RecipientEmail  string
	ExpiresAt       sql.NullTime
	CreatedAt       time.Time
	FileName        string
	FileSize        int64
	FileContentType string
	FileStorageKey  string
}

func (q *Queries) GetShareByToken(ctx context.Context, token string) (GetShareByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getShareByToken, token)
	var i GetShareByTokenRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.Token,
		&i.RecipientEmail,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FileName,
		&i.FileSize,
		&i.FileContentType,
		&i.FileStorageKey,
	)
	return i, err
}

const listSharesByFile = `-- name: ListSharesByFile :many
SELECT id, file_id, user_id, token, recipient_email, expires_at, created_at
FROM shares
WHERE file_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSharesByFile(ctx context.Context, fileID uuid.UUID) ([]Share, error) {
	rows, err := q.db.QueryContext(ctx, listSharesByFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Share
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.UserID,
			&i.Token,
			&i.RecipientEmail,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
