package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/aws/aws-lambda-go/events"

	"github.com/gasmod/gas"
	"github.com/gasmod/gas-examples/lambda-worker/db"
)

// LambdaConfig holds settings specific to this Lambda function.
// Bound from ConfigProvider at startup — the validate tag ensures the
// queue URL is set before any invocation can fail on it.
type LambdaConfig struct {
	NotificationQueueURL string `json:"notification_queue_url" validate:"required"`
}

// Handler holds resolved dependencies for the Lambda function. Registered
// as a singleton in the DI container — its constructor receives all deps
// automatically, just like a gas.Service in a web app. All fields are
// backed by connection pools, so reuse across invocations is safe.
type Handler struct {
	logger  gas.Logger
	queries *db.Queries
	queue   gas.JobQueueProvider
	cfg     LambdaConfig
}

// NewHandler is the DI constructor. The container injects all parameters.
// Config binding and validation happen here — if NotificationQueueURL is
// missing, the worker fails at startup, not at first invocation.
func NewHandler(
	logger gas.Logger,
	dbProvider gas.DatabaseProvider,
	queue gas.JobQueueProvider,
	cfgProvider gas.ConfigProvider,
) (*Handler, error) {
	var cfg LambdaConfig
	if err := cfgProvider.Bind(&cfg); err != nil {
		return nil, err
	}

	return &Handler{
		logger:  logger,
		queries: db.New(dbProvider.DB()),
		queue:   queue,
		cfg:     cfg,
	}, nil
}

// Handle processes SQS events. Each SQS record is an independent message.
func (h *Handler) Handle(ctx context.Context, event events.SQSEvent) (events.SQSEventResponse, error) {
	var failures []events.SQSBatchItemFailure

	for _, record := range event.Records {
		if err := h.processRecord(ctx, record); err != nil {
			h.logger.Error("failed to process record").
				Str("message_id", record.MessageId).
				Err("error", err).
				Send()

			// Report partial failure — SQS will retry only this message.
			failures = append(failures, events.SQSBatchItemFailure{
				ItemIdentifier: record.MessageId,
			})
		}
	}

	return events.SQSEventResponse{BatchItemFailures: failures}, nil
}

// OrderEvent is an example payload from the SQS queue.
type OrderEvent struct {
	OrderID    string `json:"order_id"`
	CustomerID string `json:"customer_id"`
	Amount     int    `json:"amount"`
}

func (h *Handler) processRecord(ctx context.Context, record events.SQSMessage) error {
	var order OrderEvent
	if err := json.Unmarshal([]byte(record.Body), &order); err != nil {
		return fmt.Errorf("unmarshal order: %w", err)
	}

	h.logger.Info("processing order").
		Str("order_id", order.OrderID).
		Str("customer_id", order.CustomerID).
		Int("amount", order.Amount).
		Send()

	// Type-safe query generated by sqlc — no raw SQL strings.
	if err := h.queries.UpdateOrderStatus(ctx, db.UpdateOrderStatusParams{
		Status: "processing",
		ID:     order.OrderID,
	}); err != nil {
		return fmt.Errorf("update order: %w", err)
	}

	// Enqueue downstream work to another queue.
	payload, _ := json.Marshal(map[string]string{
		"order_id":    order.OrderID,
		"customer_id": order.CustomerID,
	})

	if err := h.queue.Enqueue(ctx, h.cfg.NotificationQueueURL, payload); err != nil {
		return fmt.Errorf("enqueue notification: %w", err)
	}

	return nil
}
